name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instala dependências
        run: npm install

      - name: Inicia aplicação
        run: npm start &
        env:
          CI: true

      - name: Aguarda a aplicação subir
        run: npx wait-on http://localhost:3000

      - name: Executa testes Cypress
        run: npx cypress run

      - name: Upload dos vídeos dos testes (se falhar ou passar)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload dos screenshots (em caso de erro)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
